interface LanguageTranslations {
    it: string
}

const Translations = new Map<string, LanguageTranslations>([
    ["Add new style:", {it: "Aggiungi nuovo stile:"}],
    ["Style name:", {it: "Nome dello stile:"}],
    ["Style type:", {it: "Tipo dello stile:"}],
    ["Paragraph", {it: "Paragrafo"}],
    ["Character", {it: "Carattere"}],
    ["List", {it: "Lista"}],
    ["Table", {it: "Tabella"}],
    ["Show this style as a quick style in Word's \"Styles\" tab", {it: "Mostra questo stile come stile rapido nella sezione \"Stili\" di Word"}],
    ["Inside border", {it: "Bordo interno"}],
    ["Outside border", {it: "Bordo esterno"}],
    ["Color", {it: "Colore"}],
    ["Type", {it: "Tipo"}],
    ["Width", {it: "Larghezza"}],
    ["Specific border options", {it: "Opzioni specifiche dei bordi"}],
    ["Inside border", {it: "Bordo interno"}],
    ["Outside border", {it: "Bordo esterno"}],
    ["Top border", {it: "Bordo in alto"}],
    ["Bottom border", {it: "Bordo in basso"}],
    ["Left border", {it: "Bordo a sinistra"}],
    ["Right border", {it: "Bordo a destra"}],
    ["InsideHorizontal border", {it: "Bordo interno orizzontale"}],
    ["InsideVertical border", {it: "Bordo interno verticale"}],
    ["All borders", {it: "Tutti i bordi"}],
    ["Border width", {it: "Larghezza del bordo"}],
    ["Border type", {it: "Tipo del bordo"}],
    ["Discard the changes made to this property", {it: "Elimina le modifiche fatte a questa proprietà"}],
    ["Bold", {it: "Grassetto"}],
    ["Italic", {it: "Corsivo"}],
    ["Strikethrough", {it: "Barrato"}],
    ["Double Strikethrough", {it: "Doppio barrato"}],
    ["Superscript", {it: "Apice"}],
    ["Subscript", {it: "Pedice"}],
    ["Underline", {it: "Sottolineato"}],
    ["Size (in points)", {it: "Dimensione (in punti)"}],
    ["Font name", {it: "Nome del font"}],
    ["Highlight color", {it: "Colore dell'evidenziatore"}],
    ["Table cell spacing", {it: "Spazio delle celle in una tabella"}],
    ["You can choose how much empty space there should be around each cell.", {it: "Puoi scegliere quanto spazio vuoto ci dovrebbe essere attorno ad ogni cella."}],
    ["Value unit", {it: "Unità del valore"}],
    ["points", {it: "punti"}],
    ["Paragraph indent", {it: "Indentazione del paragrafo"}],
    ["By changing the paragraph indent value, you can put some empty space before the first line. You can both put a positive value (image 1) or a negative value (image 2)", {it: "Cambiando il valore dell'indentazione del paragrafo, puoi mettere un po' di spazio vuoto prima dell'inizio della prima linea. Puoi mettere sia un valore positivo (immagine 1) o un valore negativo (immagine 2)"}],
    ["List number format", {it: "Formato dei numeri della lista:"}],
    ["You can change how the numbers or bullet points should be displayed, by adding some text before or after them. In the image example, the", {it: "Puoi cambiare come i numeri o i punti dovrebbero essere mostrati, aggiungendo del testo prima o dopo di essi. Nell'esempio,"}],
    ["text has been added after the number", {it: "è stato aggiunto dopo il numero"}],
    ["Second line position", {it: "Posizione della seconda linea:"}],
    ["With this property, you can change the space before the start of every line after the first one. For example, in the first image this property was set to a normal value, while in the second one was set to", {it: "Con questa proprietà, puoi cambiare lo spaizo prima dell'inizio di ogni linea dopo la prima. Ad esempio, nella prima immagine questa proprietà è stata impostata ad un valore normale, mentre nella seconda è stato impostato su"}],
    ["Table with some empty space around each cell", {it: "Tabella con dello spazio vuoto attorno ad ogni cella"}],
    ["Paragraph with indent positive applied: the text of the first line starts after if compared to the text of the other lines", {it: "Pagrafo con indentazione positiva applicata: il testo della prima liena parte dopo rispetto al testo delle altre linee"}],
    ["Paragraph with indent negative applied: the text of the first line starts before the text of the other lines", {it: "Paragrafo con indentazione negativa applicata: il testo della prima liena inizia prima rispetto al testo delle altre linee"}],
    ["Custom number format", {it: "Formato del numero personalizzato"}],
    ["Normal second line position property", {it: "Posizione della seconda linea impostata su un valore normale"}],
    ["Second line position set to 40: the text of the second and third line is positioned more at the right than the first line", {it: "Posizione della seconda linea impostata su 40: il testo della seconda e terza linea è posizionato più a destra rispetto alla prima linea"}],
    ["Keep paragraph on the same line", {it: "Mantieni paragrafo sulla stessa linea"}],
    ["As the title says, if this option is enabled, the paragraph will be put in the same page as the paragraph which follows it. Note that, in the video, the last two lines of the Lorem ipsum have been made a new line", {it: "Come dice il titolo, se quest'opzione è abilitata, il paragrafo viene messo nella stessa pagina del paragrafo che lo segue. Nota che, nel video, le ultime due linee del Lorem ipsum sono state messe come nuova linea"}],
    ["Keep paragraph on the same page", {it: "Mantieni paragrafo sulla stessa pagina:"}],
    ["If enabled, all the lines of the paragraph will be kept in the same page. So, if at least one line should go in a new page, all the paragraph will be put in the new page", {it: "Se abilitato, tutte le linee del paragrafo verranno mantenute sulla stessa pagina. Quindi, se almeno una liena dovesse andare in una nuova pagina, tutto il paragrafo sarebbe messo nella nuova pagina."}],
    ["Shading options", {it: "Opzioni di shading"}],
    ["With shading options, you can customize the background color of the paragraph. Here you can see an example, done by mixing red and yellow and by setting the shading type to", {it: "Con le opzioni di shading, puoi personalizzare il colore di sfondo. Qui puoi vedere un esempio, creato mischiando il rosso ed il giallo e impostando il tipo dell'ombreggiatura su"}],
    ["Custom shading", {it: "Shading personalizzato"}],
    ["Level outline", {it: "Livello del testo"}],
    ["The level the paragraph should be displayed if a summary is generated, from 1 to 9. If it shouldn't be displayed,", {it: "Il livello del paragrafo utilizzato nei sommari/indici, da 1 a 9. Nel caso non dovesse comparire, usare"}],
    [" should be selected", {it: ""}],
    ["Tab position", {it: "Posizione della tabulazione"}],
    ["Choose how much tabulation space should be added between the number/bullet point and the first character of the list. If you haven't set it, you might see a really high value. This is normal, but know that usually setting it of a few tens of points is more than enough (since setting it to a high value, like thousands of points, will cause Word to reject the style change)", {it: "Scegli quanto spazio dovrebbe esserci tra il numero/punto ed il primo caratterre della lista. Se non lo hai personalizzato, potresti vedere un valore molto alto. Questo è normale, ma tieni a mente che impostarlo su un valore basso (come qualche decina) è sufficiente (visto che, se impostato ad un valore alto, come migliaia di punti, potrebbe impedire il salvataggio dello stile)"}],
    ["Close", {it: "Chiudi"}],
    ["First item on a list, with a lot of spcae between the number and the first character", {it: "Primo elemento della lista, con molto spazio tra il numero ed il primo carattere"}],
    ["Is an ordered (numeric) list", {it: "È una lista ordinata (numerica)"}],
    ["Position number", {it: "Posizione numero"}],
    ["Alignment", {it: "Allineamento"}],
    ["Unknown", {it: "Sconosciuto"}],
    ["Left", {it: "Sinistra"}],
    ["Centered", {it: "Centrato"}],
    ["Right", {it: "Destra"}],
    ["Justified", {it: "Giustificato"}],
    ["An item of list level", {it: "Un elemento della lista di livello"}],
    ["should appear before restarting counting from 1", {it: "dovrebbe apparire prima di riniziare il conteggio da 1"}],
    ["Blank spaces", {it: "Spazi vuoti"}],
    ["Blank space (in points) at the left of the list", {it: "Spazio vuoto (in punti) a sinistra della lista"}],
    ["Position (in points) of the second line of text", {it: "Posizione (in punti) della seconda linea di testo"}],
    ["After the number/symbol, add a:", {it: "Dopo il numero/simbolo, aggiungi uno/a:"}],
    ["tabulation", {it: "tabulazione"}],
    ["space", {it: "spazio"}],
    ["nothing", {it: "niente"}],
    ["Number-specific list options", {it: "Opzioni specifiche degli elenchi numerici"}],
    ["Number format", {it: "Formato del numero"}],
    ["Number style", {it: "Stile del numero,"}],
    ["Starting number of the list", {it: "Numero iniziale della lista"}],
    ["Font options (probably won't work)", {it: "Opzioni del font (probabilmente non funzionerà)"}],
    ["Next paragraph style", {it: "Stile del prossimo paragrafo"}],
    ["Make this style a quick style", {it: "Imposta questo stile come stile rapido"}],
    ["Make this style visible in the \"Recommended style\" tab", {it: "Imposta questo stile come visibile nella sezione degli \"Stili suggeriti\""}],
    ["Make this style visible in the \"Recommended style\" tab after it has been used", {it: "Imposta questo stile come visible nella sezione degli \"Stili suggeriti\" dopo che è stato usato"}],
    ["Priority", {it: "Priorità"}],
    ["Base style", {it: "Stile base"}],
    ["Indent (in points)", {it: "Indentazione (in punti)"}],
    ["Keep all the lines of the paragraph in the same page", {it: "Mantieni tutte le linee del paragrafo sulla stessa pagina"}],
    ["Put this paragraph in the same page as the next paragraph", {it: "Metti questo paragrafo nella stessa pagina del prossimo paragrafo"}],
    ["Avoid sending the second or last line to a new page (the first or second-last line will be moved too)", {it: "Evita di mandare la seconda o l'ultima linea in una nuova pagina (anche la prima o la penultima linea sarà spostata)"}],
    ["Level", {it: "Livello"}],
    ["Indentation", {it: "Indentazione"}],
    ["Left", {it: "Sinistra"}],
    ["Right", {it: "Destra"}],
    ["Spacing", {it: "Spaziatura"}],
    ["Line spacing", {it: "Spaziatura di ogni linea"}],
    ["Space before the paragraph", {it: "Spazio prima del paragrafo"}],
    ["Space after the paragraph", {it: "Spazio dopo del paragrafo"}],
    ["Foreground color", {it: "Colore principale"}],
    ["Background color", {it: "Colore dello sfondo"}],
    ["Texture type", {it: "Tipo della texture"}],
    ["The lines can be broken across pages", {it: "Le linee possono essere spezzate tra le pagine"}],
    ["Cell spacing", {it: "Spazio della cella"}],
    ["Cell margin", {it: "Margine della cella"}],
    ["Change Word styles using the Office.JS API", {it: "Cambia gli stili di Word utilizzando le API di Office.JS"}],
    ["Change styles", {it: "Cambia stili"}],
    ["Change the styles of your document, and create new ones.", {it: "Cambia gli stili del tuo documento, e creane di nuovi."}],
    ["Load styles", {it: "Carica stili"}],
    ["Apply style", {it: "Applica stile"}],
    ["Apply a style to the text you've selected on Word", {it: "Applica uno stile al testo che hai selezionato su Word"}],
    ["Change selection", {it: "Cambia selezione"}],
    ["Change how the selected text looks, without creating a new style", {it: "Cambia come viene mostrato il testo, senza creare un nuovo stile"}],
    ["Get selection", {it: "Ottieni selezione"}],
    ["Export styles", {it: "Esporta stili"}],
    ["You'll be able to choose which styles to export in a JSON file", {it: "Potrai scegliere quali stili esportare in un file JSON"}],
    ["Import styles", {it: "Importa stili"}],
    ["If you've exported a JSON file before, you can import its styles here", {it: "Se hai già esportato un file JSON, puoi importare i suoi stili qui"}],
    ["If a style with the same name is found", {it: "Se uno stile con lo stesso nome viene trovato"}],
    ["overwrite it", {it: "Sovrascrivilo"}],
    ["ignore it", {it: "Ignoralo"}],
    ["keep both of them", {it: "Mantienili entrambi"}],
    ["Pick JSON file", {it: "Scegli il file JSON"}],
    ["Font", {it: "Font"}],
    ["Paragraph", {it: "Paragrafo"}],
    ["Border", {it: "Bordo"}],
    ["Shading (background color)", {it: "Shading (colore di sfondo)"}],
    ["Table", {it: "Table"}],
    ["List order", {it: "Ordine della lista"}],
    ["General options", {it: "Opzioni generali"}],
    ["Font options", {it: "Opzioni del font"}],
    ["Paragraph options", {it: "Opzioni dei paragrafi"}],
    ["Border options", {it: "Opzioni dei bordi"}],
    ["General options", {it: "Opzioni generali"}],
    ["Shading options", {it: "Opzioni di shading"}],
    ["Table options", {it: "Opzioni della tabella"}],
    ["List options", {it: "Opzioni della lista"}],
    ["Save", {it: "Salva"}],
    ["Discard edits", {it: "Scarta modifiche"}],
    ["Apply this style", {it: "Applica questo stile"}],
    ["Apply", {it: "Applica"}],
    ["Apply changes", {it: "Applica modifiche"}],
    ["Pick the properties you want to export. To avoid freezes when importing, choose only the properties you've changed.", {it: "Seleziona le proprietà che vuoi esportare. Per evitare dei blocchi durante l'importazione, seleziona solo le proprietà che hai cambiato."}],
    ["Export", {it: "Esporta"}],
    ["Toggle all checkboxes", {it: "Alterna la selezione"}],
    ["Do you want to go back to the home?", {it: "Vuoi tornare alla home?"}],
    ["You'll lose all the unsaved changes.", {it: "Perderai tutte le modifiche non salvate."}],
    ["Yes", {it: "Sì"}],
    ["No", {it: "No"}],
    ["Download file", {it: "Scarica file"}],
    ["Unfortunately, the platform you're using doesn't support file downloading. Copy the link displayed below, and then open it in your browser. Don't worry, your ultra-personal styles will always be private, and they aren't uploaded anywhere (all the download process happens locally).", {it: "Sfortunatamente, la piattaforma che stai usando non supporta il download dei file. Copia il link mostrato qui sotto, ed aprilo nel tuo browser. Non preoccuparti i tuoi stili rimarranno sempre privati, e non sono stati caricati da nessuna parte (tutto il processo del download avviene localmente)."}],
    ["Copy", {it: "Copia"}],
    ["View open source licenses", {it: "Visualizza licenze open source"}],
    ["Change theme", {it: "Cambia tema"}],
    ["Open source licenses", {it: "Licenze open source"}],
    ["Select one of the following open source libraries to see its license", {it: "Seleziona una delle librerie open source usate per vedere la sua licenza"}],
    ["An error occurred", {it: "Si è verificato un errore"}],
    ["Here you can change the selected lists. Note that you need to save the settings in this section every time you edit a level, not at the end with the \"Apply edits\" button outside this card.", {it: "Qui puoi cambiare le liste selezionate. Nota che devi salvare queste impostazioni manualmente ogni volta che hai modificato un livello, e non col pulsante \"Applica modifiche\" fuori da questa card."}],
    ["Edit level", {it: "Modifica livello"}],
    ["Don't change", {it: "Non cambiarlo"}],
    ["Change bullet type", {it: "Cambia il tipo di punto"}],
    ["Bullet type", {it: "Tipo di punto"}],
    ["Custom character", {it: "Carattere personalizzato"}],
    ["Font of the custom character", {it: "Font del carattere personalizzato"}],
    ["Change indentation", {it: "Cambia indentazione"}],
    ["Text indentation", {it: "Indentazione del testo"}],
    ["Space left at the left of the bullet point", {it: "Spazio lasciato a sinistra del punto elenco"}],
    ["Change number type", {it: "Cambia la tipologia di numero"}],
    ["Number type", {it: "Tipo di numero"}],
    ["Use an image for the current bullet point", {it: "Utilizza un'immagine per il punto elenco corrente"}],
    ["Change the starting number of the list", {it: "Cambia il numero d'inizio della lista"}],
    ["Start from", {it: "Inizia da"}],
    ["Lists", {it: "Liste"}],
    ["You can reference the values of the current level by writing", {it: "Puoi far riferimento ai valori del livello corrente scrivendo"}],
    ["You can reference previous levels by writing the dollar sign followed by the list level, and then another dollar sign", {it: "Puoi far riferimento a valori di livelli precedenti scrivendo il segno del dollaro, seguito dal livello della lista e da un altro segno del dollaro"}],
    ["If you need to use the dollar sign everywhere else, write", {it: "Se devi usare il segno del dollaro da qualsiasi altra parte, scrivi"}],
    ["(without the closing dollar sign!)", {it: "(senza il simbolo del dollaro alla fine!)"}],
    ["Write here the number format. Note that:", {it: "Scrivi qui il formato del numero. Nota che:"}],
    ["Change the number format", {it: "Cambia il formato del numero"}],
    ["Word and Office are trademarks of Microsoft. This project is no way affiliated or endorsed by Microsoft", {it: "Word e Office sono marchi di Microsoft. Questo progetto non è in alcun modo affiliato o sponsorizzato da Microsoft"}],
    ["GIF where the second last paragraph goes to the new page with the last paragraph", {it: "GIF dove il penultimo paragrafo viene spostato in una nuova pagina con l'ultimo paragrafo"}],
    ["GIF where the entire paragraph goes to a new page", {it: "GIF dove l'intero paragrafo viene spostato in una nuova pagina"}]
])

let isOfficeReady = false;
export const updateOfficeReady = () => (isOfficeReady = true);

export function lang(str: string) {
    if (!isOfficeReady) return str;
    const temp = Translations.get(str);
    if (temp) return temp[Office.context.displayLanguage.substring(0, 2) as "it"] ?? str;
    return str;
}